import { defineCollection } from '../../store/filedb.js';
import { softDelete } from '../common/counter.model.js';

export const FinanceExpense = defineCollection('finance_expenses', {
  ...softDelete,
  expenseKey: '',
  title: '',
  category: 'Other',
  amount: 0,
  expenseDate: '',
  status: 'Draft',
  paymentMode: '',
  payeeName: '',
  contactId: null,
  remarks: '',
  createdById: null,
  createdByEmail: '',
  approvedById: null,
  approvedAt: null,
  isActive: true,
});

export const FinanceInvoice = defineCollection('finance_invoices', {
  ...softDelete,
  invoiceKey: '',
  invoiceNumber: '',
  /** Alias used in UI as bill number (same as invoiceNumber). */
  billNumber: '',
  vendorName: '',
  contactId: null,
  amount: 0,
  taxAmount: 0,
  totalAmount: 0,
  invoiceDate: '',
  billDate: '',
  dueDate: '',
  status: 'draft',
  paymentMode: '',
  linkedInOutId: null,
  grnEntryId: null,
  poDocumentId: null,
  campId: null,
  assetRequestId: null,
  expenseCategory: '',
  expenseSubCategory: '',
  expenseSubCategoryId: null,
  attachments: [],
  attachmentUrl: '',
  attachmentFileName: '',
  attachmentMimeType: '',
  attachmentStoredName: '',
  verificationRemark: '',
  rejectionReason: '',
  paidAmount: 0,
  transactionId: '',
  paymentRemark: '',
  paidAt: null,
  archivedAt: null,
  submittedAt: null,
  submittedById: null,
  submittedByEmail: '',
  verifiedAt: null,
  verifiedById: null,
  verifiedByEmail: '',
  approvedById: null,
  approvedByEmail: '',
  approvedAt: null,
  remarks: '',
  createdById: null,
  createdByEmail: '',
  isActive: true,
});

/** Singleton org letterhead / bank details for commercial PDFs */
export const FinanceOrgProfile = defineCollection('finance_org_profile', {
  _id: 'default',
  legalName: '',
  brandLine: '',
  cin: '',
  pan: '',
  gstin: '',
  state: '',
  stateCode: '',
  registeredOffice: '',
  phone: '',
  email: '',
  website: '',
  udyam: '',
  udyamLabel: '',
  bankName: '',
  accountHolder: '',
  accountNumber: '',
  ifscCode: '',
  bankBranch: '',
  upiId: '',
  logoDataUrl: '',
  paymentQrDataUrl: '',
  defaultPaymentTermsDays: 45,
  defaultTerms: [],
  proformaNotes: [],
  defaultPoTerms: [],
  defaultPurchaseTaxRate: 5,
  updatedById: null,
  updatedByEmail: '',
});

/** Proforma, client invoice, purchase order */
export const FinanceCommercialDocument = defineCollection('finance_commercial_documents', {
  ...softDelete,
  docKey: '',
  documentType: 'proforma',
  documentNumber: '',
  fiscalYear: '',
  documentPeriod: '',
  status: 'Draft',
  source: 'generated',
  clientId: null,
  clientMasterId: null,
  recipientName: '',
  projectName: '',
  placeOfSupply: '',
  deliveryAddress: '',
  contactPerson: '',
  contactEmail: '',
  recipientGstin: '',
  recipientPan: '',
  recipientStateCode: '',
  reference: '',
  referenceDate: '',
  servicePeriod: '',
  cnReference: '',
  originalInvoiceDate: '',
  creditReason: '',
  debitReason: '',
  dnReference: '',
  receiptVoucher: '',
  documentDate: '',
  dueDate: '',
  paymentTermsDays: 0,
  reverseCharge: 'N',
  lineItems: [],
  subtotal: 0,
  cnAmount: 0,
  dnAmount: 0,
  advanceReceived: 0,
  roundOff: 0,
  taxAmount: 0,
  grandTotal: 0,
  amountInWords: '',
  taxMode: 'igst',
  purchaseTaxRate: 5,
  contactId: null,
  terms: [],
  customNotes: '',
  declaration: '',
  shipToName: '',
  shipToContactPerson: '',
  shipToAddress: '',
  shipToGstin: '',
  shipToStateCode: '',
  shipToStateName: '',
  recipientStateName: '',
  vehicleNo: '',
  transporterName: '',
  /** Delivery challan logistics */
  dispatchDate: '',
  expectedDeliveryDate: '',
  fromCompanyName: '',
  fromAddress: '',
  fromGstin: '',
  fromContactPerson: '',
  fromMobile: '',
  fromEmail: '',
  recipientType: '',
  deliverToCompany: '',
  deliverToMobile: '',
  courierName: '',
  awbNo: '',
  courierMode: '',
  packageCount: '',
  originCity: '',
  destinationCity: '',
  purposeOfMovement: '',
  packedBy: '',
  checkedBy: '',
  dispatchedBy: '',
  receivedBy: '',
  receivedMobile: '',
  conditionOnReceipt: '',
  receivedDate: '',
  /** Full Invoice Builder UI form for round-trip edit fidelity */
  builderForm: null,
  uploadedFileName: '',
  uploadedMimeType: '',
  storageKey: '',
  submittedAt: null,
  submittedById: null,
  submittedByEmail: '',
  approvedAt: null,
  approvedById: null,
  approvedByEmail: '',
  issuedAt: null,
  cancelledAt: null,
  cancelledById: null,
  cancelledByEmail: '',
  /** Receipt against issued commercial documents (Billing Center). */
  paidAmount: 0,
  paymentStatus: 'Unpaid',
  paidAt: null,
  paidById: null,
  paidByEmail: '',
  createdById: null,
  createdByEmail: '',
  updatedById: null,
  updatedByEmail: '',
  isActive: true,
});
