import { defineCollection } from '../../store/filedb.js';
import { softDelete } from '../common/counter.model.js';

export const FinanceExpense = defineCollection('finance_expenses', {
  ...softDelete,
  expenseKey: '',
  title: '',
  category: 'Other',
  amount: 0,
  expenseDate: '',
  status: 'Draft',
  paymentMode: '',
  payeeName: '',
  contactId: null,
  remarks: '',
  createdById: null,
  createdByEmail: '',
  approvedById: null,
  approvedAt: null,
  isActive: true,
});

export const FinanceInvoice = defineCollection('finance_invoices', {
  ...softDelete,
  invoiceKey: '',
  invoiceNumber: '',
  vendorName: '',
  contactId: null,
  amount: 0,
  taxAmount: 0,
  totalAmount: 0,
  invoiceDate: '',
  dueDate: '',
  status: 'Open',
  paymentMode: '',
  linkedInOutId: null,
  remarks: '',
  createdById: null,
  createdByEmail: '',
  isActive: true,
});

/** Singleton org letterhead / bank details for commercial PDFs */
export const FinanceOrgProfile = defineCollection('finance_org_profile', {
  _id: 'default',
  legalName: '',
  brandLine: '',
  cin: '',
  pan: '',
  gstin: '',
  state: '',
  stateCode: '',
  registeredOffice: '',
  phone: '',
  email: '',
  website: '',
  bankName: '',
  accountNumber: '',
  ifscCode: '',
  bankBranch: '',
  defaultPaymentTermsDays: 45,
  defaultTerms: [],
  proformaNotes: [],
  defaultPoTerms: [],
  defaultPurchaseTaxRate: 5,
  updatedById: null,
  updatedByEmail: '',
});

/** Proforma, client invoice, purchase order */
export const FinanceCommercialDocument = defineCollection('finance_commercial_documents', {
  ...softDelete,
  docKey: '',
  documentType: 'proforma',
  documentNumber: '',
  fiscalYear: '',
  documentPeriod: '',
  status: 'Draft',
  source: 'generated',
  clientId: null,
  clientMasterId: null,
  recipientName: '',
  projectName: '',
  placeOfSupply: '',
  deliveryAddress: '',
  contactPerson: '',
  contactEmail: '',
  recipientGstin: '',
  recipientPan: '',
  recipientStateCode: '',
  reference: '',
  cnReference: '',
  dnReference: '',
  receiptVoucher: '',
  documentDate: '',
  dueDate: '',
  paymentTermsDays: 0,
  reverseCharge: 'N',
  lineItems: [],
  subtotal: 0,
  cnAmount: 0,
  dnAmount: 0,
  advanceReceived: 0,
  roundOff: 0,
  taxAmount: 0,
  grandTotal: 0,
  amountInWords: '',
  taxMode: 'igst',
  purchaseTaxRate: 5,
  contactId: null,
  terms: [],
  customNotes: '',
  uploadedFileName: '',
  uploadedMimeType: '',
  storageKey: '',
  issuedAt: null,
  createdById: null,
  createdByEmail: '',
  isActive: true,
});
