export const ASSET_STATUSES = [
  'Purchased',
  'Received',
  'Warehouse',
  'Available',
  'Assigned',
  'Verified',
  'Maintenance',
  'Repair',
  'Retired',
  'Disposed',
];

/** fromStatus -> allowed toStatuses */
export const ASSET_TRANSITIONS = {
  Purchased: ['Received'],
  Received: ['Warehouse'],
  Warehouse: ['Available', 'Retired'],
  Available: ['Assigned', 'Retired', 'Maintenance', 'Repair'],
  Assigned: ['Verified', 'Maintenance', 'Repair', 'Retired', 'Available'],
  Verified: ['Assigned', 'Maintenance', 'Repair', 'Retired'],
  Maintenance: ['Warehouse', 'Available', 'Assigned'],
  Repair: ['Warehouse', 'Available', 'Assigned', 'Retired'],
  Retired: ['Disposed'],
  Disposed: [],
};

export const PERMISSIONS = {
  ALL: '*',
  ASSETS_READ: 'assets:read',
  ASSETS_WRITE: 'assets:write',
  ASSETS_TRANSITION: 'assets:transition',
  ASSETS_VIEW_VALUE: 'assets:view-value',
  MOVEMENTS_READ: 'movements:read',
  MOVEMENTS_REQUEST: 'movements:request',
  MOVEMENTS_APPROVE: 'movements:approve',
  VERIFICATIONS_READ: 'verifications:read',
  VERIFICATIONS_WRITE: 'verifications:write',
  AGREEMENTS_READ: 'agreements:read',
  AGREEMENTS_WRITE: 'agreements:write',
  REPAIRS_READ: 'repairs:read',
  REPAIRS_WRITE: 'repairs:write',
  MAINTENANCE_WRITE: 'maintenance:write',
  DOCUMENTS_WRITE: 'documents:write',
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  HCWS_WRITE: 'hcws:write',
  AUDIT_READ: 'audit:read',
  IMPORTS_EXECUTE: 'imports:execute',
  DASHBOARDS_READ: 'dashboards:read',
  NOTIFICATIONS_READ: 'notifications:read',
  DEVICES_WRITE: 'devices:write',
  MASTERS_READ: 'masters:read',
  /** In-House Camp Management */
  CAMPS_READ: 'camps:read',
  CAMPS_REQUEST: 'camps:request',
  CAMPS_APPROVE: 'camps:approve',
};

export const ROLE_PERMISSIONS = {
  Admin: [PERMISSIONS.ALL],
  AssetManager: [
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.ASSETS_WRITE,
    PERMISSIONS.ASSETS_TRANSITION,
    PERMISSIONS.ASSETS_VIEW_VALUE,
    PERMISSIONS.MOVEMENTS_REQUEST,
    PERMISSIONS.AGREEMENTS_READ,
    PERMISSIONS.AGREEMENTS_WRITE,
    PERMISSIONS.REPAIRS_WRITE,
    PERMISSIONS.MAINTENANCE_WRITE,
    PERMISSIONS.DOCUMENTS_WRITE,
    PERMISSIONS.HCWS_WRITE,
    PERMISSIONS.DEVICES_WRITE,
    PERMISSIONS.IMPORTS_EXECUTE,
    PERMISSIONS.CAMPS_READ,
    PERMISSIONS.CAMPS_REQUEST,
    PERMISSIONS.DASHBOARDS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  Verifier: [
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.VERIFICATIONS_READ,
    PERMISSIONS.VERIFICATIONS_WRITE,
    PERMISSIONS.DASHBOARDS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.DOCUMENTS_WRITE,
  ],
  Approver: [
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.MOVEMENTS_READ,
    PERMISSIONS.MOVEMENTS_REQUEST,
    PERMISSIONS.MOVEMENTS_APPROVE,
    PERMISSIONS.CAMPS_READ,
    PERMISSIONS.CAMPS_APPROVE,
    PERMISSIONS.DASHBOARDS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  Viewer: [
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.AGREEMENTS_READ,
    PERMISSIONS.VERIFICATIONS_READ,
    PERMISSIONS.DASHBOARDS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.CAMPS_READ,
    PERMISSIONS.CAMPS_REQUEST,
  ],
  CampRequester: [
    PERMISSIONS.CAMPS_READ,
    PERMISSIONS.CAMPS_REQUEST,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  CampApprover: [
    PERMISSIONS.CAMPS_READ,
    PERMISSIONS.CAMPS_REQUEST,
    PERMISSIONS.CAMPS_APPROVE,
    PERMISSIONS.DASHBOARDS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
};

export const PHYSICAL_CHECK = ['PASS', 'FAIL'];
export const FUNCTIONALITY_CHECK = ['CHECKED', 'NOT_CHECKED'];
/** @deprecated use PHYSICAL_CHECK / FUNCTIONALITY_CHECK */
export const CHECKLIST = PHYSICAL_CHECK;
