import { defineCollection } from '../../store/filedb.js';
import { softDelete } from '../common/counter.model.js';

export const CampRequest = defineCollection('camp_requests', {
  ...softDelete,
  requestKey: '',
  method: '',
  process: '',
  campType: '',
  doctorName: '',
  address: '',
  city: '',
  state: '',
  campDate: '',
  startTime: '',
  endTime: '',
  campSlot: '',
  /** Hours (3–8); endTime derived when set */
  durationHours: 3,
  expectedPatients: 0,
  actualPatients: 0,
  screenCount: 0,
  fieldPersonName: '',
  fieldPersonPhone: '',
  technicianName: '',
  technicianNumber: '',
  technicianContactId: null,
  status: 'Pending',
  decisionReason: '',
  decidedAt: null,
  decidedById: null,
  decidedByEmail: '',
  /** Brand | Ops — who cancelled an approved camp */
  cancelledBy: '',
  cancelledAt: null,
  completedAt: null,
  completedById: null,
  completedByEmail: '',
  requestedAt: '',
  requesterId: null,
  requesterEmail: '',
  requesterName: '',
  remarks: '',
  isActive: true,
});
