/**
 * Camp Download / full export columns aligned with Camp One lifecycle form labels.
 * Keep labels in sync with CampLifecycleForm.jsx field captions.
 */

export const CAMP_SOURCE_LABELS = {
  dashboard: 'Dashboard',
  email: 'Email',
  whatsapp: 'WhatsApp',
  excel: 'Excel Import',
  paste: 'Manual Paste',
  api: 'API',
  parser: 'Request Parser',
};

export const CAMP_EXPORT_SECTIONS = [
  {
    id: 'overview',
    label: 'Overview',
    columns: [
      { key: 'campId', label: 'Camp ID' },
      { key: 'status', label: 'Camp Status' },
      { key: 'lifecycleStage', label: 'Lifecycle Stage' },
      { key: 'requestReviewStatusLabel', label: 'Request Review Status' },
      { key: 'sourceLabel', label: 'Source of Request' },
      { key: 'requestDate', label: 'Request Date' },
    ],
  },
  {
    id: 'request',
    label: 'Request',
    columns: [
      { key: 'clientName', label: 'Client Name' },
      { key: 'campaignType', label: 'Division / Therapy' },
      { key: 'campaignName', label: 'Method' },
      { key: 'campDate', label: 'Camp Date' },
      { key: 'startTime', label: 'Camp Start Time' },
      { key: 'endTime', label: 'Camp End Time' },
      { key: 'durationHours', label: 'Duration (Hours)' },
      { key: 'campSlot', label: 'Camp Slot' },
      { key: 'timeFrameRange', label: 'Time Frame' },
      { key: 'doctorName', label: 'Doctor Name' },
      { key: 'doctorCode', label: 'Doctor Code' },
      { key: 'speciality', label: 'Doctor Type / Specialty' },
      { key: 'campAddress', label: 'Camp / Clinic Address' },
      { key: 'googlePlaceId', label: 'Google Place ID' },
      { key: 'pincode', label: 'PIN Code' },
      { key: 'state', label: 'State' },
      { key: 'zone', label: 'Zone' },
      { key: 'district', label: 'District' },
      { key: 'city', label: 'City' },
      { key: 'hq', label: 'HQ' },
      { key: 'contactPersonLevel', label: 'Contact Person Level' },
      { key: 'fieldPersonName', label: 'Contact Person Name' },
      { key: 'expectedPatients', label: 'Expected Patients' },
      { key: 'fieldPersonPhone', label: 'Contact Person Number' },
      { key: 'remarks', label: 'Remarks' },
    ],
  },
  {
    id: 'review_closure',
    label: 'Review & Closure',
    columns: [
      { key: 'rejectionReason', label: 'Refusal Reason' },
      { key: 'informationRequestNote', label: 'Information Requested' },
      { key: 'cancelledByLabel', label: 'Cancelled By' },
      { key: 'assignmentRefusalReason', label: 'Closure Type' },
      { key: 'closureReasonCategory', label: 'Closure Reason' },
      { key: 'closureSubReasonLabel', label: 'Closure Sub-Reason' },
      { key: 'cancellationReason', label: 'Cancellation / Refusal Remark' },
    ],
  },
  {
    id: 'assignment',
    label: 'Assignment',
    columns: [
      { key: 'assignmentStatus', label: 'Assignment Status' },
      { key: 'hcwCategory', label: 'HCW Category' },
      { key: 'hcwName', label: 'HCW Name' },
      { key: 'hcwContact', label: 'HCW Contact' },
    ],
  },
  {
    id: 'execution',
    label: 'Execution',
    columns: [
      { key: 'executionStatus', label: 'Execution Status' },
      { key: 'chargeableStatus', label: 'Chargeable Status' },
      { key: 'inTime', label: 'In Time' },
      { key: 'outTime', label: 'Out Time' },
      { key: 'totalHours', label: 'Total Hours (Auto)' },
      { key: 'extraHours', label: 'Extra Hours (Auto)' },
      { key: 'kmRoundTrip', label: 'KM (Round Trip)' },
      { key: 'punctuality', label: 'Punctuality (Auto)' },
      { key: 'attire', label: 'Attire' },
      { key: 'labCoat', label: 'Lab Coat' },
      { key: 'patientsCount', label: 'Patients Count' },
      { key: 'rxCount', label: 'Rx Count' },
      { key: 'doctorFormCount', label: 'DF (Doctor Form)' },
      { key: 'patientFormCount', label: 'PF (Patient Form)' },
      { key: 'otherDocCount', label: 'Others' },
      { key: 'gpsSelfieCount', label: 'GPS Selfie' },
      { key: 'consumablesUsedSummary', label: 'Consumables Used' },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    columns: [
      { key: 'campRevenue', label: 'Camp Revenue' },
      { key: 'overtimeRevenue', label: 'Overtime Revenue' },
      { key: 'otherRevenue', label: 'Other Revenue' },
      { key: 'totalRevenue', label: 'Total Revenue (Auto)' },
      { key: 'campAmount', label: 'Camp Amount' },
      { key: 'travelling', label: 'Travelling' },
      { key: 'overtimeExpense', label: 'Overtime' },
      { key: 'otherExpenses', label: 'Other Expenses' },
      { key: 'totalPayout', label: 'Total Payout (Auto)' },
      { key: 'paymentSubmitStatus', label: 'Payment check' },
      { key: 'financePaymentStatus', label: 'Finance status' },
      { key: 'paidAmount', label: 'Paid Amount' },
      { key: 'transactionId', label: 'Transaction ID / UTR' },
      { key: 'balance', label: 'Balance' },
      { key: 'paymentRemark', label: 'Payment Remark' },
      { key: 'submittedToFinanceAt', label: 'Submitted to Finance At' },
    ],
  },
];

export function getCampExportColumns() {
  const used = new Set();
  const columns = [];
  for (const section of CAMP_EXPORT_SECTIONS) {
    for (const column of section.columns) {
      if (used.has(column.key)) continue;
      used.add(column.key);
      columns.push(column);
    }
  }
  return columns;
}

export const CAMP_EXPORT_SAMPLE_ROW = {
  campId: '26-08-0001',
  status: 'Approved',
  lifecycleStage: 'Camp Execution',
  requestReviewStatusLabel: 'Pending review',
  sourceLabel: 'Dashboard',
  requestDate: '30/07/2026',
  clientName: 'Demo Pharma Ltd',
  campaignType: 'Screening',
  campaignName: 'BMD',
  campDate: '15/08/2026',
  startTime: '11:00',
  endTime: '15:00',
  durationHours: 4,
  campSlot: 'Morning',
  timeFrameRange: '11:00 – 15:00',
  doctorName: 'Dr Example',
  doctorCode: 'D001',
  speciality: 'General Practitioner',
  campAddress: '12 Main Street, Andheri',
  pincode: '400001',
  state: 'Maharashtra',
  zone: 'West Zone',
  district: 'Mumbai City',
  city: 'Mumbai',
  hq: 'Mumbai',
  contactPersonLevel: 'Territory Manager',
  fieldPersonName: 'Rep One',
  expectedPatients: 40,
  fieldPersonPhone: '9999999999',
  remarks: 'Sample camp row',
  assignmentStatus: 'Assigned',
  hcwCategory: 'Technician',
  hcwName: 'HCW Name',
  hcwContact: '9888888888',
  executionStatus: 'Camp Completed',
  chargeableStatus: 'Chargeable',
  inTime: '11:05',
  outTime: '15:10',
  totalHours: 4.08,
  extraHours: 0.08,
  kmRoundTrip: 24,
  punctuality: 'Good',
  attire: 'No Issues',
  labCoat: 'No Issues',
  patientsCount: 38,
  rxCount: 12,
  doctorFormCount: 1,
  patientFormCount: 1,
  otherDocCount: 0,
  gpsSelfieCount: 1,
  consumablesUsedSummary: 'Test Strip | 20 | 2; Device Battery | 2 | 0',
  campRevenue: 5000,
  overtimeRevenue: 0,
  otherRevenue: 0,
  totalRevenue: 5000,
  campAmount: 3500,
  travelling: 500,
  overtimeExpense: 0,
  otherExpenses: 0,
  totalPayout: 4000,
  paymentSubmitStatus: 'Validation Completed',
  financePaymentStatus: 'Under Review',
  paidAmount: 0,
  transactionId: '',
  balance: 4000,
  paymentRemark: '',
  submittedToFinanceAt: '',
};
