import { defineCollection } from '../../store/filedb.js';
import { softDelete } from '../common/counter.model.js';

export const CampOpsCamp = defineCollection('camp_ops_camps', {
  ...softDelete,
  campId: '',
  clientId: null,
  clientName: '',
  campaignId: null,
  campaignName: 'BMD',
  campaignType: 'Screening',
  doctorName: '',
  doctorCode: '',
  scCode: '',
  mslNo: '',
  speciality: '',
  hospitalName: '',
  clinicName: '',
  campAddress: '',
  city: '',
  state: '',
  pincode: '',
  campDate: '',
  startTime: '09:00',
  endTime: '12:00',
  durationHours: 3,
  expectedPatients: 0,
  actualPatients: 0,
  fieldPersonName: '',
  fieldPersonPhone: '',
  source: 'dashboard',
  status: 'pending_review',
  cancelledBy: '',
  remarks: '',
  createdById: null,
  createdByEmail: '',
  approvedById: null,
  approvedByEmail: '',
  executedById: null,
  executedByEmail: '',
  executedAt: null,
  submittedAt: null,
  submittedOffHours: false,
  submittedWeekendAttention: false,
  isActive: true,
});

export const CampOpsClient = defineCollection('camp_ops_clients', {
  ...softDelete,
  name: '',
  code: '',
  isActive: true,
});

export const CampOpsClientMaster = defineCollection('camp_ops_client_masters', {
  ...softDelete,
  clientId: null,
  clientName: '',
  programName: '',
  drugTherapyName: '',
  campName: 'BMD',
  campType: '',
  coordinatorName: '',
  healthcareWorker: '',
  poAmount: 0,
  campDuration: '',
  spocName: '',
  spocNumber: '',
  requestTimeline: '',
  executedCampUnit: 0,
  cancelledCampUnit: 0,
  otUnit: 0,
  minimumPatientCovered: 0,
  minimumKmsCovered: 0,
  extPatientUnit: 0,
  kmsUnit: 0,
  isActive: true,
  createdById: null,
  updatedById: null,
});

export const CampOpsCampaign = defineCollection('camp_ops_campaigns', {
  ...softDelete,
  clientId: null,
  clientName: '',
  name: '',
  division: '',
  isActive: true,
});

export const CampOpsImportTemplate = defineCollection('camp_ops_import_templates', {
  ...softDelete,
  name: '',
  mapping: {},
  createdById: null,
  createdByEmail: '',
});
