import { defineCollection } from '../../store/filedb.js';
import { softDelete } from '../common/counter.model.js';

export const CampOpsCamp = defineCollection('camp_ops_camps', {
  ...softDelete,
  campId: '',
  clientId: null,
  clientName: '',
  campaignId: null,
  campaignName: 'BMD',
  campaignType: 'Screening',
  doctorName: '',
  doctorCode: '',
  scCode: '',
  mslNo: '',
  speciality: '',
  hospitalName: '',
  clinicName: '',
  campAddress: '',
  city: '',
  state: '',
  district: '',
  pincode: '',
  latitude: null,
  longitude: null,
  campDate: '',
  startTime: '09:00',
  endTime: '12:00',
  durationHours: 3,
  expectedPatients: 0,
  actualPatients: 0,
  fieldPersonName: '',
  fieldPersonPhone: '',
  source: 'dashboard',
  lifecycleStage: 'request',
  requestDate: '',
  hq: '',
  zone: '',
  campSlot: '',
  assignmentDecision: '',
  assignmentRefusalReason: '',
  hcwContactId: null,
  assignmentStatus: 'Pending',
  hcwCategory: '',
  hcwName: '',
  hcwContact: '',
  executionStatus: 'Pending',
  cancellationReason: '',
  closureReasonCode: '',
  chargeableStatus: '',
  inTime: '',
  inTimeSelfieUrl: '',
  outTime: '',
  totalHours: null,
  extraHours: 0,
  kmRoundTrip: 0,
  punctuality: '',
  attire: '',
  labCoat: '',
  rxCount: 0,
  executionDocuments: [],
  campRevenue: 0,
  overtimeRevenue: 0,
  otherRevenue: 0,
  totalRevenue: 0,
  campAmount: 0,
  travelling: 0,
  overtimeExpense: 0,
  otherExpenses: 0,
  totalPayout: 0,
  paidAmount: 0,
  balance: 0,
  transactionId: '',
  paymentRemark: '',
  paymentSubmitStatus: '',
  financePaymentStatus: '',
  submittedToFinanceAt: null,
  submittedToFinanceById: null,
  submittedToFinanceByEmail: '',
  financeProcessedAt: null,
  financeProcessedById: null,
  financeProcessedByEmail: '',
  status: 'pending_review',
  cancelledBy: '',
  remarks: '',
  createdById: null,
  createdByEmail: '',
  approvedById: null,
  approvedByEmail: '',
  executedById: null,
  executedByEmail: '',
  executedAt: null,
  submittedAt: null,
  submittedOffHours: false,
  submittedWeekendAttention: false,
  requestReviewStatus: 'review_pending',
  reviewOverdueAt: null,
  informationRequestNote: '',
  informationRequestedAt: null,
  informationRequestedById: null,
  informationRequestedByEmail: '',
  rejectionReason: '',
  whatsappMessageId: '',
  whatsappSenderPhone: '',
  whatsappRawMessage: '',
  emailIngestId: '',
  emailMessageId: '',
  emailSender: '',
  emailSubject: '',
  emailRawBody: '',
  isActive: true,
});

export const CampOpsClient = defineCollection('camp_ops_clients', {
  ...softDelete,
  name: '',
  code: '',
  isActive: true,
});

export const CampOpsClientMaster = defineCollection('camp_ops_client_masters', {
  ...softDelete,
  clientId: null,
  clientName: '',
  programName: '',
  drugTherapyName: '',
  campName: 'BMD',
  campType: '',
  coordinatorName: '',
  healthcareWorker: '',
  poAmount: 0,
  campDuration: '',
  spocName: '',
  spocNumber: '',
  requestTimeline: '',
  executedCampUnit: 0,
  cancelledCampUnit: 0,
  otUnit: 0,
  minimumPatientCovered: 0,
  minimumKmsCovered: 0,
  extPatientUnit: 0,
  kmsUnit: 0,
  isActive: true,
  createdById: null,
  updatedById: null,
});

export const CampOpsCampaign = defineCollection('camp_ops_campaigns', {
  ...softDelete,
  clientId: null,
  clientName: '',
  name: '',
  division: '',
  isActive: true,
});

export const CampOpsImportTemplate = defineCollection('camp_ops_import_templates', {
  ...softDelete,
  name: '',
  mapping: {},
  createdById: null,
  createdByEmail: '',
});

export const CampOpsInboundEmail = defineCollection('camp_ops_inbound_emails', {
  ...softDelete,
  messageId: '',
  imapUid: null,
  from: '',
  subject: '',
  bodyText: '',
  html: '',
  receivedAt: '',
  attachments: [],
  channel: 'imap',
  status: 'inbox',
  isCampaignCandidate: false,
  matchSummary: '',
  skipReason: '',
  previewData: null,
  linkedCampIds: [],
  processedAt: null,
  archivedAt: null,
  archivedById: null,
  processedById: null,
});

export const CampOpsEmailIngestConfig = defineCollection('camp_ops_email_ingest_config', {
  allowedDomains: [],
  allowedSenders: [],
  keywords: [],
  updatedById: null,
});

export const CampOpsParserAudit = defineCollection('camp_ops_parser_audit', {
  originalMessage: '',
  parsed: null,
  clientId: '',
  clientName: '',
  parserUsed: '',
  timestamp: '',
  actorId: null,
  actorEmail: '',
});
