import { defineCollection } from '../../store/filedb.js';
import { softDelete, archiveFields } from '../common/counter.model.js';

export const CampOpsCamp = defineCollection('camp_ops_camps', {
  ...softDelete,
  ...archiveFields,
  campId: '',
  clientId: null,
  clientName: '',
  campaignId: null,
  campaignName: 'BMD',
  campaignType: 'Screening',
  doctorName: '',
  doctorCode: '',
  scCode: '',
  mslNo: '',
  speciality: 'General Practitioner',
  hospitalName: '',
  clinicName: '',
  campAddress: '',
  googlePlaceId: '',
  addressManualEntry: false,
  city: '',
  state: '',
  district: '',
  pincode: '',
  latitude: null,
  longitude: null,
  campDate: '',
  startTime: '09:00',
  endTime: '12:00',
  durationHours: 3,
  expectedPatients: 0,
  actualPatients: 0,
  fieldPersonName: '',
  fieldPersonPhone: '',
  contactPersonLevel: '',
  contactPersons: [],
  source: 'dashboard',
  lifecycleStage: 'request',
  requestDate: '',
  hq: '',
  zone: '',
  campSlot: '',
  assignmentDecision: '',
  assignmentRefusalReason: '',
  hcwContactId: null,
  assignmentStatus: 'Unassigned',
  /** Set when a Hiring Request is submitted in Request One from this camp */
  hiringRequestedAt: null,
  hiringRequestId: null,
  hiringRequestNumber: '',
  hcwCategory: '',
  hcwName: '',
  hcwContact: '',
  /** True when HCW was assigned with < 30m gap; needs Reporting Manager approval. */
  hcwGapOverridePendingApproval: false,
  hcwGapOverrideAcknowledgedAt: null,
  executionStatus: 'Camp Scheduled',
  cancellationReason: '',
  closureReasonCode: '',
  closureReasonCategory: '',
  closureSubReason: '',
  closureSubReasonLabel: '',
  chargeableStatus: '',
  inTime: '',
  inTimeSelfieUrl: '',
  outTime: '',
  totalHours: null,
  extraHours: 0,
  kmRoundTrip: 0,
  punctuality: '',
  attire: '',
  labCoat: '',
  rxCount: 0,
  executionDocuments: [],
  consumablesUsed: [],
  campRevenue: 0,
  travelRevenue: 0,
  overtimeRevenue: 0,
  otherRevenue: 0,
  totalRevenue: 0,
  campAmount: 0,
  travelling: 0,
  overtimeExpense: 0,
  otherExpenses: 0,
  totalPayout: 0,
  netContribution: 0,
  paidAmount: 0,
  balance: 0,
  transactionId: '',
  paymentRemark: '',
  paymentSubmitStatus: '',
  financePaymentStatus: '',
  expenseCategory: '',
  expenseSubCategory: '',
  expenseSubCategoryId: null,
  submittedToFinanceAt: null,
  submittedToFinanceById: null,
  submittedToFinanceByEmail: '',
  financeProcessedAt: null,
  financeProcessedById: null,
  financeProcessedByEmail: '',
  status: 'pending_review',
  cancelledBy: '',
  remarks: '',
  createdById: null,
  createdByEmail: '',
  approvedById: null,
  approvedByEmail: '',
  executedById: null,
  executedByEmail: '',
  executedAt: null,
  submittedAt: null,
  submittedOffHours: false,
  submittedWeekendAttention: false,
  requestReviewStatus: 'review_pending',
  reviewOverdueAt: null,
  executionOverdueNotifiedAt: null,
  requestIncomplete: false,
  informationRequestNote: '',
  informationRequestedAt: null,
  informationRequestedById: null,
  informationRequestedByEmail: '',
  rejectionReason: '',
  whatsappMessageId: '',
  whatsappSenderPhone: '',
  whatsappRawMessage: '',
  emailIngestId: '',
  emailMessageId: '',
  emailSender: '',
  emailSubject: '',
  emailRawBody: '',
  isActive: true,
});

export const CampOpsClient = defineCollection('camp_ops_clients', {
  ...softDelete,
  name: '',
  code: '',
  /**
   * Optional company-level defaults (legacy). Client Master program rows own their own
   * billing (GSTIN/PAN/address) per Client + GSTIN + Division + Method.
   */
  address: '',
  gstin: '',
  pan: '',
  stateName: '',
  stateCode: '',
  contactPerson: '',
  email: '',
  phone: '',
  isActive: true,
});

export const CampOpsClientMaster = defineCollection('camp_ops_client_masters', {
  ...softDelete,
  clientId: null,
  clientName: '',
  programName: '',
  displayName: '',
  drugTherapyName: '',
  campName: 'BMD',
  campType: '',
  coordinatorName: '',
  healthcareWorker: [],
  campDuration: '',
  /** Per-row billing — independent for each Client + GSTIN + Division + Method */
  billingAddress: '',
  billingGstin: '',
  billingPan: '',
  billingStateName: '',
  billingStateCode: '',
  spocName: '',
  spocNumber: '',
  spocEmail: '',
  requestTimeline: '',
  assignedUserEmails: [],
  campTerms: 'none',
  campTermsFiles: [],
  purchaseOrders: [],
  poCombinedNet: 0,
  poCombinedGst: 0,
  poCombinedGross: 0,
  // Legacy / PO Based fields
  poNumber: '',
  poNetValue: 0,
  poApplyGst18: false,
  poGstAmount: 0,
  poGrossValue: 0,
  poIssueDate: '',
  poExpiryDate: '',
  poFile: null,
  agreementStartDate: '',
  agreementEffectiveDate: '',
  agreementEndDate: '',
  executedCampUnit: 0,
  cancelledCampUnit: 0,
  otUnit: 0,
  minimumPatientCovered: 0,
  minimumKmsCovered: 0,
  extPatientUnit: 0,
  kmsUnit: 0,
  mappedConsumables: [],
  isActive: true,
  createdById: null,
  updatedById: null,
});

export const CampOpsCampaign = defineCollection('camp_ops_campaigns', {
  ...softDelete,
  clientId: null,
  clientName: '',
  name: '',
  division: '',
  isActive: true,
});

export const CampOpsImportTemplate = defineCollection('camp_ops_import_templates', {
  ...softDelete,
  name: '',
  mapping: {},
  createdById: null,
  createdByEmail: '',
});

export const CampOpsExportTemplate = defineCollection('camp_ops_export_templates', {
  ...softDelete,
  name: '',
  columns: [],
  filters: {},
  format: 'xlsx',
  createdById: null,
  createdByEmail: '',
});

export const CampOpsInboundEmail = defineCollection('camp_ops_inbound_emails', {
  ...softDelete,
  messageId: '',
  imapUid: null,
  from: '',
  subject: '',
  bodyText: '',
  html: '',
  receivedAt: '',
  attachments: [],
  channel: 'imap',
  status: 'inbox',
  isCampaignCandidate: false,
  matchSummary: '',
  skipReason: '',
  previewData: null,
  linkedCampIds: [],
  processedAt: null,
  archivedAt: null,
  archivedById: null,
  processedById: null,
});

export const CampOpsEmailIngestConfig = defineCollection('camp_ops_email_ingest_config', {
  allowedDomains: [],
  allowedSenders: [],
  keywords: [],
  updatedById: null,
});

export const CampOpsParserAudit = defineCollection('camp_ops_parser_audit', {
  originalMessage: '',
  parsed: null,
  clientId: '',
  clientName: '',
  parserUsed: '',
  timestamp: '',
  actorId: null,
  actorEmail: '',
});
