/** Contact Directory excel columns — aligned with Contact form labels. */

export const CONTACT_HEADERS = [
  'Name',
  'Email',
  'Contact Category',
  'Resource Type',
  'Profession / Role',
  'Organization Name',
  'Supply Category',
  'Contact',
  'City',
  'State',
  'Address',
  'PIN Code',
  'PAN Number',
  'IFSC Code',
  'Bank Name',
  'Account Number',
  'Service Provider (agency)',
];

export const CONTACT_SAMPLE_ROWS = [
  [
    'Dr. Ananya Rao',
    'ananya@example.com',
    'Resource',
    'Full-Time',
    'Doctor',
    '',
    '',
    '9876543210',
    'Hyderabad',
    'Telangana',
    '12 Health Park Road',
    '500081',
    'ABCDE1234F',
    'HDFC0001234',
    'HDFC Bank',
    '123456789012',
    '',
  ],
  [
    'City Hospital',
    'ops@cityhospital.example',
    'Client',
    '',
    '',
    'City Hospital Group',
    '',
    '9123456780',
    'Mumbai',
    'Maharashtra',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
];
